-- FK 제약 조건 비활성화
SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE productinfo;
ALTER TABLE productinfo ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE bom;
ALTER TABLE bom ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE plan;
ALTER TABLE plan ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE stocks;
ALTER TABLE stocks ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE inbound;
ALTER TABLE inbound ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE outbound;
ALTER TABLE outbound ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE purchase;
ALTER TABLE purchase ALTER COLUMN id RESTART WITH 1;

TRUNCATE TABLE outbounddetails;
ALTER TABLE outbounddetails ALTER COLUMN id RESTART WITH 1;

-- FK 제약 조건 다시 활성화
SET REFERENTIAL_INTEGRITY TRUE;